version: '3.8'
services:
   web:
    image: nginx:alpine
    restart: always
    volumes:
     
      # see https://github.com/matomo-org/matomo-nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
